server:
  port: 9876

db:
  username: postgres
  password: pass
#  pool:
#    size: 12
#  driver: PostgresDriverFromProps
  url: jdbc:postgresql://localhost:5430/postgres

spring:
  profiles:
#    active: native
    active: spring-jdbc