server:
  port: 9876

db:
  username: postgres
  password: pass
#  pool:
#    size: 12
#  driver: PostgresDriverFromProps
  url: postgres:5432

spring:
  profiles:
    active: native
#    active: spring-jdbc