server:
  port: 9876

spring:
  application:
    name: first-step
  profiles:
    #    active: native
    #    active: spring-jdbc
    active: spring-jpa

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  cloud:
    discovery:
      enabled: false
      client:
        simple:
          enabled: false

method:
  trace:
    enabled: true
    threshold-ms: 100              # 0 - чтобы логировались все методы
    time-unit: MILLISECONDS
    annotation-required: true    # true - логируем только методы с @TraceMethod
    log-level: INFO
    log-parameters: false
    log-result: false
